
-- ANALYTICAL QUERIES

-- Q1 Find total revenue generated by each product category.
select p.category, ifnull(sum(pm.amount),0) as revenue
from products p inner join order_details using(product_id) join orders using(order_id) join payments pm using(order_id)
group by p.category;

-- Q2 Find the top 5 selling products by quantity.
with cte as(
select p.product_name, sum(o.quantity) as total_quantity from products p inner join order_details o using(product_id)
group by product_name)
select * from ( select *, dense_rank() over(order by total_quantity desc) as rnk from cte)t 
where rnk<=5;

-- Q3 Find customers who made more than one purchase.
select customer_id, count(*) 
from orders group by customer_id having count(*)>1;

-- Q4 Find the highest spending customer.
select o.customer_id, sum(p.amount) as spending 
from orders o inner join order_details using(order_id) inner join payments p using(order_id)
group by o.customer_id 
order by spending desc 
limit 1;

-- Q5 Find monthly sales revenue.
select month(o.order_date) as months, sum(p.amount) as monthly_revenue 
from orders o inner join order_details using(order_id) inner join payments p using(order_id) group by months;

-- Q6 Rank products by revenue within each category using DENSE_RANK().
with cte as(
select p.product_name,p.category, sum(pm.amount) as revenue
from products p inner join order_details using(product_id) inner join payments pm using(order_id) group by p.product_id)
select *, dense_rank() over(partition by category order by revenue desc) as rnk from cte;

-- Q7 Find the cumulative sales revenue by order date.
select o.order_date, sum(sum(pm.amount)) over(order by order_date) as cum_revuenue 
from orders o inner join payments pm using(order_id) group by order_date;

-- Q8 Create a VIEW showing order summary
-- (customer_name, product_name, quantity, revenue).
desc products;
create view view4 as(
select c.customer_name, p.product_name, sum(od.quantity) as total_quantity , sum(pm.amount) as revenue
from customers c join orders o using(customer_id) join order_details od using(order_id) 
 join products p using(product_id) join payments pm using(order_id) group by c.customer_name, p.product_name);
select * from view4;

desc payments;
-- Q9 Using a CTE find customers whose total spending
-- is greater than average spending.
with cte as (
select c.customer_name, sum(pm.amount) as spendings 
from customers c join orders using(customer_id) join payments pm using(order_id) 
group by c.customer_name)
select * from cte where spendings> (select avg(spendings) from cte);

-- Q10 Find products that have never been ordered.
select p.product_name, sum(od.quantity) 
from products p inner join order_details od using(product_id) 
group by product_name having sum(od.quantity)=0;

-- Q11 Find the most expensive product purchased in each order.
select *from (
select o.order_id, p.product_name, p.price, row_number() over( partition by o.order_id order by p.price desc) as rnk
from orders o
join order_details od using(order_id) join products p using(product_id)) t
where rnk = 1;

-- Q12 Find second highest priced product in each category.
select *from (
select o.order_id, p.product_name, p.price, row_number() over( partition by o.order_id order by p.price desc) as rnk
from orders o
join order_details od using(order_id) join products p using(product_id)) t
where rnk = 2;

-- Q13 Find the percentage contribution of each product
-- to total sales using window functions.
select p.product_name, SUM(pm.amount) as product_sales,
round(sum(pm.amount) * 100.0 / sum(sum(pm.amount)) over(), 2) as percentage_contribution
from orders o join order_details od using(order_id) join products p using(product_id) join payments pm using(order_id)
group by p.product_name;

desc orders;
-- Q14 Find customers who purchased products from multiple categories.
select c.customer_name, count(distinct(p.category)) as count 
from customers c join orders using(customer_id) join order_details using(order_id)
join products p using(product_id)
group by c.customer_name having count(distinct(p.category))>1;

-- Q15 Find the most popular payment method.
select payment_method, count(*) as count 
from payments group by payment_method 
order by count desc limit 1;
