-- =====================================
-- REVENUE ANALYSIS
-- =====================================

-- Q1 Total revenue generated by each restaurant
SELECT r.restaurant_name, IFNULL(SUM(t.total_amount),0) AS total
FROM restaurants r
LEFT JOIN orders t ON t.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name;

-- Q2 Top 3 customers by spending
SELECT c.customer_name, SUM(t.total_amount) AS total
FROM customers c
JOIN orders t ON c.customer_id = t.customer_id
GROUP BY c.customer_id
ORDER BY total DESC
LIMIT 3;

-- Q3 Restaurants with no orders
SELECT restaurant_name
FROM restaurants
WHERE restaurant_id NOT IN (
SELECT restaurant_id FROM orders
);

-- =====================================
-- OPERATIONAL ANALYSIS
-- =====================================

-- Q4 Orders delivered by each agent
SELECT a.agent_name, COUNT(o.order_id) AS no_of_orders
FROM orders o
JOIN delivery_agents a USING(agent_id)
GROUP BY agent_id;

-- Q5 Most popular food item
SELECT i.item_name, COUNT(o.order_id) AS no_of_items
FROM orders o
JOIN order_items i USING(order_id)
GROUP BY i.item_name
ORDER BY no_of_items DESC
LIMIT 1;

-- =====================================
-- WINDOW FUNCTION ANALYSIS
-- =====================================

-- Q6 Rank restaurants by revenue within each city
WITH cte1 AS (
SELECT r.restaurant_name, r.city, SUM(o.total_amount) AS revenue
FROM orders o
JOIN restaurants r USING(restaurant_id)
GROUP BY r.restaurant_id
)
SELECT restaurant_name, city, revenue,
DENSE_RANK() OVER(PARTITION BY city ORDER BY revenue DESC) AS rnk
FROM cte1;

-- Q7 Running revenue by order date
SELECT order_date,
SUM(total_amount) AS daily_revenue,
SUM(SUM(total_amount)) OVER(ORDER BY order_date) AS running_total_revenue
FROM orders
GROUP BY order_date;

-- =====================================
-- CUSTOMER BEHAVIOR ANALYSIS
-- =====================================

-- Q8 Customers ordering from multiple restaurants
SELECT c.customer_id, COUNT(o.restaurant_id)
FROM customers c
JOIN orders o USING(customer_id)
GROUP BY c.customer_id
HAVING COUNT(*) > 1;

-- Q9 Create order summary view
CREATE VIEW view1 AS
SELECT c.customer_id, r.restaurant_name, o.order_date, o.total_amount
FROM orders o
JOIN customers c USING(customer_id)
JOIN restaurants r USING(restaurant_id);

-- Q10 Customers spending above average
WITH cte1 AS (
SELECT customer_id, SUM(total_amount) AS total_spents
FROM orders
GROUP BY customer_id
)
SELECT *
FROM cte1
WHERE total_spents > (
SELECT AVG(total_spents) FROM cte1
);

-- =====================================
-- ADVANCED ANALYTICS
-- =====================================

-- Q11 Second highest order value
WITH cte1 AS (
SELECT *, DENSE_RANK() OVER(ORDER BY total_amount DESC) AS rnk
FROM orders
)
SELECT *
FROM cte1
WHERE rnk = 2;

-- Q12 Most expensive item in each order
SELECT oi.order_id, oi.item_name, oi.price,
ROW_NUMBER() OVER(PARTITION BY oi.order_id ORDER BY oi.price DESC) AS rnk
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id;

-- Q13 Restaurants with above average revenue
WITH cte1 AS (
SELECT r.restaurant_name, SUM(o.total_amount) AS revenue
FROM restaurants r
JOIN orders o USING(restaurant_id)
GROUP BY r.restaurant_id
)
SELECT *
FROM cte1
WHERE revenue > (
SELECT AVG(revenue) FROM cte1
);

-- Q14 City with highest revenue
WITH cte1 AS (
SELECT r.city, SUM(o.total_amount) AS revenue
FROM orders o
JOIN restaurants r USING(restaurant_id)
GROUP BY city
)
SELECT *
FROM cte1
ORDER BY revenue DESC
LIMIT 1;

-- Q15 Customers ordering on consecutive days
SELECT DISTINCT c.customer_id, c.customer_name
FROM orders o1
JOIN orders o2
ON o1.customer_id = o2.customer_id
AND DATEDIFF(o2.order_date, o1.order_date) = 1
JOIN customers c ON c.customer_id = o1.customer_id;